blog/urls.py
from django.urls import path
from .views import post_detail,post_List,post_share

app_name = 'blog'

urlpatterns = [
    path('',post_List, name="post_list"),

    path('tag/<slug:tag_slug>/',post_List, name='post_list_by_tag'),

    path('<int:year>/<int:month>/<int:day>/<slug:post>/',post_detail,name="post_detail"),
    path('<int:post_id>/share/',post_share, name='post_share'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include("blog.urls", namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.urls import reverse
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

from taggit.managers import TaggableManager



class Post(models.Model):
    STATUS_CHOICES = (
        ('draft','Draft'),
        ('published','Published'),
    )
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name="blog_posts")
    body = models.TextField()
    image = models.ImageField(upload_to="images/")
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    uptade = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')

    tags = TaggableManager()


    class Meta:
        ordering = ('-publish',)
        verbose_name_plural = "postlar"

    def __str__(self):
        return self.title


    def get_absalute_url(self):
        return reverse('blog:post_detail',args=[self.publish.year,self.publish.month,self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name="comments")
    name = models.CharField(max_length=255)
    email  = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    activate = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)
        verbose_name_plural = "Comentlar"

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from .models import Comment
from  django  import forms


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    to = forms.EmailField()
    Comments = forms.CharField(required=False,widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','email','body')

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Post
from django.core.paginator import  Paginator,PageNotAnInteger, EmptyPage

from .forms import EmailPostForm,CommentForm
from django.core.mail import send_mail
from django.conf import settings

from taggit.models import Tag




def post_List(request,tag_slug=None):
    object_list = Post.objects.filter(status="published")

    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 1)
    page = request.GET.get("page")
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(Paginator.num_pages)
    context = {
        "posts":posts,
        "page":page,
        "tag":tag,
    }
    return render(request, 'blog/post/list.html',context)





def post_detail(request,year,month,day,post):
    post = get_object_or_404(
        Post,
        slug=post,
        status='published',
        publish__year = year,
        publish__month = month,
        publish__day = day 
    )
    
    comments = post.comments.filter(activate=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post 
            new_comment.save()
    else:
        comment_form = CommentForm()

    context = {
        "post":post,
        "comments":comments,
        "new_comment": new_comment,
        "comment_form":comment_form,
        
    }
    return render(request, 'blog/post/detail.html',context)


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False 
    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleand_date
            post_url = request.bulid_absalute_uri(post.get_absalute_url())
            subject = f"{cd['name']} sizga {post.title} ni oqishni tavsiya qiladi. "
            message = f"Salom yaxshimisiz . Quyidagi linkdagi postni oqib koring. {post_url}\n\nComents:{cd['comments']}"
            send_mail(subject,message,settings.EMAIL_HOST_USER, [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/blog.css'%}">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div id="content">
        {% block content %}

        {% endblock %}
    </div>
    <div id="sidebar">
        <h2>Birinchi proyekt</h2>
        <p>blog</p>
        
    </div>
</body>
</html>

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% block title %}Birinchi proyekt {% endblock%}
{% block content %}
    <img  style=" margin-top: 30px;" src=" {{ post.image.url}}" alt="">
    <h1>{{ post.title }}</h1>

        <p class="date">
            Published  {{ post.Publish }} by {{ post.author }}
        </p>
        {{ post.body|linebreaks }}
        <p>
            <a href="{% url 'blog:post_share' post.id%}">
                Ulashish
            </a>
        </p>
        {% with comments.count as total_comments %}
        <h2>
           {{ total_comments }} comment{{ total_comments|pluralize }} 
        </h2>
        {% endwith %}
        {% for comment in comments %}
            <div class="comment">
                <p class="info">
                    Comment {{ forloop.counter }} by {{ comment.name }}
                    {{ comment.created }}
                </p>
                {{ comment.body|linebreaks }}
            </div>
            {% empty %}
            <p>Bu postda comment mavjud emas </p>
        {% endfor %}

        {% if new_comment %}
        <h2>Sizning commentingiz qoshildi </h2>
    {% else %}
        <h2>Yangi comentariya qoshish</h2>
        <form method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Qoshish"></p>
        </form>
        {% endif %}
{% endblock %}

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% block title %}Birinchi proyekt {% endblock%}
{% block content %}
    <h1>Birinchi proyekt</h1>
    {% for post in posts %}
        <a href="{{ post.get_absalute_url}}">
            <img  style="width: 500px;"  src="{{ post.image.url }}" alt="">
        </a>
        <h2>
            <a href="{{ post.get_absalute_url}}">
                {{ post.title }}
            </a>
        </h2>
        <p class="tags">
            {% for tag in post.tags.all%}
            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
            #{{ tag.name }}
            </a>
            {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        {% if tag %}
            <h2>Posts tagget with "{{tag.name }}"</h2>
        {% endif %}

        
        <p class="date">
            Published  {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|truncatewords:20|linebreaks }}

    {% endfor%}
    {% include "pagination.html" with page=posts %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html %}

{% block title %}Share a post{% endblock%}
{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ pot.title }}" was successfully sent to {{ form..cleand_date.to }}.
        </p>    
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail </h1>
        <form method="post">
            {{ form.as_p}}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}   
        <a href="?page={{ page.previous_page_number }}">Orqaga</a>
        {% endif %}
        <span class="current">
            | {{ page.number }}| 
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Keyingi</a>
        {% endif %}
    </span>
</div>